vim:
    desc:   ViM editor
    ubuntu: vim-full vim-gtk ctags
    fedora: vim-enhanced vim-X11 ctags
firebird:
    desc:   Firebird super server
    ubuntu: firebird2.1-super firebird2.1-dev
    fedora: firebird-superserver firebird-filesystem firebird-devel
postgres:
    desc:   PostgreSQL server
    ubuntu: postgresql libpq-dev libpostgresql-ocaml-dev
    fedora: postgresql postgresql-server postgresql-devel
sqlite3:
    desc:   Sqlite3 server
    debian: sqlite3 libsqlite3-dev
mysql:
    desc:   MySQL server
    debina: mysql-server libmysql++-dev
libxml2:
    desc:   XML2 library - required by Cucumber
    ubuntu: libxml2 libxml2-dev
    fedora: libxml2 libxml2-devel
libxslt1:   
    desc:   XSLT library - required by Cucumber
    ubuntu: libxslt1.1 libxslt1-dev
    fedora: libxslt libxslt-devel
build_essential:
    desc: Packages required to build native extensions
    ubuntu:
    fedora: make g++
    debian: make g++ 
